name: flutter_hashmicro_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  fluentui_system_icons: ^1.1.251
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  overlay_loading_progress: ^1.0.1
  path: ^1.9.0
  sqflite: ^2.3.3+1
  toastification: ^2.1.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  branding: assets/images/splash_brand.png

  branding_mode: bottom

  android_12:
    color: "#ffffff"
    image: assets/images/splash.png
    branding: assets/images/splash_brand.png

  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
